from enum import Enum

class RequestIdPrefix(Enum):
    TOP_GAINER_DAY_CANDLE_REQ_ID_PREFIX = 100
    TOP_GAINER_MINUTE_CANDLE_REQ_ID_PREFIX = 200
    CLOSEST_TO_HALT_DAY_CANDLE_REQ_ID_PREFIX = 1000
    CLOSEST_TO_HALT_MINUTE_CANDLE_REQ_ID_PREFIX = 1100
    HALT_DAY_CANDLE_REQ_ID_PREFIX = 2000
    HALT_MINUTE_CANDLE_REQ_ID_PREFIX = 2100
    MAXIMUM_SCANNER_RESULT_SIZE = 50